baseURL = "https://vali.link/"
languageCode = "en-us"
title = "Vali's Homepage"
theme = "webcore"

[params.IndieWeb]
    urls = [ { name = "bluesky", url = "https://bsky.app/profile/vali.link" }, { name = "twitch", url = "https://twitch.tv/vali_woof" },
        { name = "artfight", url = "https://artfight.net/~vali_woof" }, { name = "furaffinity", url = "https://www.furaffinity.net/user/valiwoof/" },
        { name ="github", url = "https://github.com/vali-woof" }, { name = "mastodon", url = "https://bark.lgbt/@vali" } ]
    feedLocation = "/posts"
    [params.IndieWeb.Hcard]
        name = "Vali"
        pronouns = [ { value = "he", href = "https://en.wiktionary.org/wiki/he#Pronoun" }, { value = "they", href = "https://en.wiktionary.org/wiki/they#Pronoun" } ]
        note = "I'm a software engineer and artist on the internet. If you want to check out some of my work, head over to the posts section of my website."
        photo = "/img/pfp-cropped.png"
    [params.IndieWeb.Webmentions]
        url = "https://webmention.io/vali.link/webmention"
        maxWebmentions = "99"

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    category = "categories"
    tag = "tags"
    posttype = "posttypes"

[permalinks]
    categories = "/:section/:slug"