baseURL = "https://vali.link/"
languageCode = "en-us"
title = "Vali's Homepage"
theme = "webcore"

[params.IndieWeb]
    urls = [ "https://bsky.app/profile/vali.link", "https://twitch.tv/vali_woof", "https://artfight.net/~vali_woof",
        "https://github.com/vali-woof", "https://bark.lgbt/@vali" ]
    feedLocation = "/posts"
    [params.IndieWeb.Hcard]
        name = "Vali"
        pronouns = [ { value = "he", href = "https://en.wiktionary.org/wiki/he#Pronoun" }, { value = "they", href = "https://en.wiktionary.org/wiki/they#Pronoun" } ]
        note = "I'm a software engineer and artist on the internet."
        photo = "/img/pfp-cropped.png"
    [params.IndieWeb.Webmentions]
        url = "https://webmention.io/vali.link/webmention"
        maxWebmentions = "99"

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    category = "categories"

[permalinks]
    categories = "/:section/:slug"